config/routes.rb
Rails.application.routes.draw do
	root 'login#index'

  get '/callback', to: 'login#callback'
  get '/landing', to: 'login#landing'
  get '/procore', to: 'login#procore'
  get '/work_order_contracts', to: 'work_order_contracts#index'
  get '/purchase_order_contracts', to: 'purchase_order_contracts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  CLIENT_ID = ENV['CLIENT_ID']
  CLIENT_SECRET = ENV['CLIENT_SECRET']
  REDIRECT_URI = ENV['REDIRECT_URI']
  OAUTH_URL = ENV['OAUTH_URL']
  BASE_URL = ENV['BASE_URL']

  private
  def logged_in
  	unless session[:oauth_response]
  		redirect_to "/landing", notice: "No token!"
  	end
  end

end

app/controllers/login_controller.rb
require 'json'
require 'rest-client'

class LoginController < ApplicationController
  before_action :logged_in, only: :index

  def index
  end

  def landing
    session[:procoreProjectId] = params[:procoreProjectId]
    session[:procoreCompanyId] = params[:procoreCompanyId]
  end

  def procore
    url = "#{ENV["OAUTH_DOMAIN"]}/oauth/authorize?response_type=code&client_id=#{ENV["CLIENT_ID"]}&redirect_uri=#{ENV["REDIRECT_URI"]}"

    redirect_to url
  end

  def callback
    @authorization_code = params["code"]

    request = {
      grant_type: "authorization_code",
      client_id: ENV["CLIENT_ID"],
      client_secret: ENV["CLIENT_SECRET"],
      code: @authorization_code,
      redirect_uri: ENV["REDIRECT_URI"]
    }

    response = RestClient.post("#{ENV["OAUTH_DOMAIN"]}/oauth/token", request.to_json, {content_type: :json, accept: :json})
    session[:oauth_response] = JSON.parse(response)
    puts session[:oauth_response]

    redirect_to root_path
  end
end

app/controllers/purchase_order_contracts_controller.rb
class PurchaseOrderContractsController < ApplicationController
	before_action :logged_in

  def index
    session[:procoreProjectId] ||= '8673'
    session[:procoreCompanyId] ||= '13958'

    if params[:search]
      query = "&filters[origin_id]=#{params[:search]}"
    else 
      query = ""
    end

    list_poc= RestClient.get("#{ENV['BASE_URL']}/vapid/purchase_order_contracts?project_id=#{session[:procoreProjectId]}#{query}",
    {"Authorization" => "Bearer #{session[:oauth_response]['access_token']}",
    "Procore-Company-ID" => session[:procoreCompanyId]})

    @purchase_order_contracts = JSON.parse(list_poc)
  end

end

app/controllers/work_order_contracts_controller.rb
class WorkOrderContractsController < ApplicationController
	before_action :logged_in

  def index
    session[:procoreProjectId] ||= '8673'
    session[:procoreCompanyId] ||= '13958'

      if params[:search]
        query = "&filters[origin_id]=#{params[:search]}"
      else 
      	query = ""
      end

    list_woc= RestClient.get("#{ENV['BASE_URL']}/vapid/work_order_contracts?project_id=#{session[:procoreProjectId]}#{query}",
    {"Authorization" => "Bearer #{session[:oauth_response]['access_token']}",
    "Procore-Company-ID" => session[:procoreCompanyId]})


    @work_order_contracts = JSON.parse(list_woc)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def view_object(name, args = {})
	  if name.is_a?(Symbol)
	    class_name = name.to_s.titleize.split(" ").join("")
	  else
	    class_name = name.split("/").map {|n| n.titleize.sub(" ", "") }.join("::")
	  end
	  class_name.constantize.new(args)
	end
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/purchase_order_contracts_helper.rb
module PurchaseOrderContractsHelper
end

app/helpers/work_order_contracts_helper.rb
module WorkOrderContractsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>External Data Viewer</title>
    <link rel="stylesheet" href="https://procore-core.global.ssl.fastly.net/latest/core-css/core.css"/>
    <%= csrf_meta_tags %>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csp_meta_tag %>

    <link
      rel="stylesheet"
      href="https://procore-core.global.ssl.fastly.net/latest/core-css/core.css"
    />
    <link rel="stylesheet" href="https://procore-core.global.ssl.fastly.net/7.2.5/core-icons/icons.css"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <body>
      <div class="wrapper">
        <%= yield %>
      </div>
    </body>
</html>

app/views/login/index.html.erb
<% javascript_include_tag '/assets/javascripts/ProcoreIframeHelpers.js' %>

<script>

  const context = procoreIframeHelpers.initialize();

  // Call notifySuccess to close the login panel. An optional payload to be passed to your
  // onSuccess handler can be included with the notifySuccess method...
  context.authentication.notifySuccess({})

</script>

<%= view_object(:nav_header).html %>

<div class="core-empty-state">
  <div class="core-empty-state__image"><img src="assets/empty_state.png" /></div>
  <div class="core-empty-state__title">Origin Data Viewer</div>
  <div class="core-empty-state__description core-sm-bold--secondary">Please click one of the tools above to display data.</div>

app/views/login/landing.html.erb
<% javascript_include_tag '/assets/javascripts/ProcoreIframeHelpers.js' %>
<% stylesheet_link_tag "/assets/stylesheets/login.css" %>
<script>
  $(document).ready(function() {

      const context = procoreIframeHelpers.initialize();

      $('#submit1').on('click', function() {

          context.authentication.authenticate({

          // Set this to a URL on your domain that will start the authentication process.
          // This URL points to a route that calls the /oauth/authorize endpoint with client_id, response_type, and redirect_uri query parameters...
          // https://login.procore.com/oauth/authorize?client_id=<ClientID>&response_type=<ResponseType>&redirect_uri=<RedirectID>
          url: "/procore",

          // Send the end user to the /main route of your iframe app if authentication is successful. This can be any route you choose.
          // You can optionally include a payload as a function parameter (i.e., function(payload))
          onSuccess: function() {
            window.location = "/"
          },

          // Error handling function that runs if authentication fails. Here we are just logging the error
          // to the console, but you will want to display an error to the user. This
          // function can be triggered by you, or will be triggered automatically if the
          // user closes the authenication window.
          onFailure: function(error) {
            console.log(error);
          }

        });

      });

  });

</script>

<% if flash[:notice] %>
  <div class="core-banner core-banner--error">
    <span aria-hidden="true" class="core-banner__icon core-icon--md ci ci-error-o"></span>
    <div class="core-banner__content">
      <div class="core-banner__title">Error</div>
      <p class="core-banner__body">Please sign in with Procore.</p>
    </div>
    <button class="core-banner__dismiss core-icon--md ci ci-x"></button>
  </div>
<% end %>

<div>
  <div class ="core-card core-padding-sm" id="login-card">
    <span class="core-lg-medium--primary">Welcome to the Origin Data Viewer!</span>
    <p class="core-md-regular--primary">To use this app, click the button below and log in with your Procore credentials. On the following page, click 'Allow' to allow the app to use your credentials to make requests for the data you have access to.</p><br />
    <button class="core-button core-button--lg core-button--primary core-button--block" id="submit1">
      <div class="core-button__label">
        Sign in to Procore
      </div>
    </button>
  </div>
</div>

app/views/purchase_order_contracts/index.html.erb
<%= view_object(:nav_header, active: :poc ).html %>
<div class="core-l-list-page__body">
  <div class="core-l-list-page__body__content">
    <div class="core-padding-lg" style={{ background: '#f5f5f5', flex: 1 }}>
      <div class="core-card core-card--level-30">
        <div className="core-icon-layout core-icon-layout--count-2">
          <%= form_tag(purchase_order_contracts_path, method: "get") do %>
            <%= text_field_tag :search, params[:search], class: "core-input", placeholder: "Search for Origin ID" %>
            <div className="core-margin-r-xs core-margin-l-xs">
              <%= submit_tag 'Submit', class: "core-button core-button--md core-button--primary" %>
            </div>
          <% end %>
        </div>
        <div class="core-table">
          <table class="core-table__table sortable">
            <thead class="core-table__head">
              <tr class="core-table__head-row">
                <th class="core-table__th">
                  <div class="core-table__th__label">
                    Title
                  </div>
                </th>
                <th class="core-table__th core-table__th--sortable core-table__th--sortable-asc">
                  <div class="core-table__th__label">
                    Number
                  </div>
                </th>
                <th class="core-table__th core-table__th--sortable">
                  <div class="core-table__th__label">
                    Origin ID
                  </div>
                </th>
                <th class="core-table__th core-table__th--sortable">
                  <div class="core-table__th__label">
                    Origin Data
                  </div>
                </th>
                <th class="core-table__th core-table__th--sortable">
                  <div class="core-table__th__label">
                    Origin Code
                  </div>
                </th>
              </tr>
            </thead>

            <tbody class="core-table__body">
              <% @purchase_order_contracts.each do |contract| %>
              <tr class="core-table__body-row">
                <td class="core-table__td">
                  <label class="core-table__text-cell">
                    <%= contract['title'] %>
                  </label>
                </td>
                <td class="core-table__td">
                  <label class="core-table__text-cell">
                    <%= contract['number'] %>
                  </label>
                </td>
                <td class="core-table__td">
                  <label class="core-table__text-cell">
                    <%= contract['origin_id'] %>
                  </label>
                </td>
                <td class="core-table__td">
                  <label class="core-table__text-cell">
                    <%= contract['origin_data'] %>
                  </label>
                </td>
                <td class="core-table__td">
                  <label class="core-table__text-cell">
                    <%= contract['origin_code'] %>
                  </label>
                </td>
              </tr>
              <% end %>
            </tbody>

            <tfoot>

            </tfoot>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/work_order_contracts/index.html.erb
<%= view_object(:nav_header, active: :woc).html %>
<div class="core-l-list-page__body">
  <div class="core-l-list-page__body__content">
    <div class="core-padding-lg" style={{ background: '#f5f5f5', flex: 1 }}>
      <div class="core-card core-card--level-30">
        <div className="core-icon-layout core-icon-layout--count-2">
          <%= form_tag(work_order_contracts_path, method: "get") do %>
            <%= text_field_tag :search, params[:search], class: "core-input", placeholder: "Search for Origin ID" %>
            <div className="core-margin-r-xs core-margin-l-xs">
              <%= submit_tag 'Submit', class: "core-button core-button--md core-button--primary" %>
            </div>
          <% end %>
        </div>
        <div class="core-table">
          <table class="core-table__table sortable">
            <thead class="core-table__head">
              <tr class="core-table__head-row">
                <th class="core-table__th">
                  <div class="core-table__th__label">
                    Title
                  </div>
                </th>
                <th class="core-table__th core-table__th--sortable core-table__th--sortable-asc">
                  <div class="core-table__th__label">
                    Number
                  </div>
                </th>
                <th class="core-table__th core-table__th--sortable">
                  <div class="core-table__th__label">
                    Origin ID
                  </div>
                </th>
                <th class="core-table__th core-table__th--sortable">
                  <div class="core-table__th__label">
                    Origin Data
                  </div>
                </th>
                <th class="core-table__th core-table__th--sortable">
                  <div class="core-table__th__label">
                    Origin Code
                  </div>
                </th>
              </tr>
            </thead>

            <tbody class="core-table__body">
              <% @work_order_contracts.each do |contract| %>
              <tr class="core-table__body-row">
                <td class="core-table__td">
                  <label class="core-table__text-cell">
                    <%= contract['title'] %>
                  </label>
                </td>
                <td class="core-table__td">
                  <label class="core-table__text-cell">
                    <%= contract['number'] %>
                  </label>
                </td>
                <td class="core-table__td">
                  <label class="core-table__text-cell">
                    <%= contract['origin_id'] %>
                  </label>
                </td>
                <td class="core-table__td">
                  <label class="core-table__text-cell">
                    <%= contract['origin_data'] %>
                  </label>
                </td>
                <td class="core-table__td">
                  <label class="core-table__text-cell">
                    <%= contract['origin_code'] %>
                  </label>
                </td>
              </tr>
              <% end %>
            </tbody>

            <tfoot>

            </tfoot>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/work_order_contracts/index_old.html.erb
<table>
  <tr>
    <th>Contract Name</th>
    <th>Contract Number</th>
    <th>Origin ID</th>
    <th>Origin Data</th>
    <th>Origin Code</th>
  </tr>
  <% @work_order_contracts.each do |contract| %>
  <tr>
    <td><%= contract['title'] %></td>
    <td><%= contract['number'] %></td>
    <td><%= contract['origin_id'] %></td>
    <td><%= contract['origin_data'] %></td>
    <td><%= contract['origin_code'] %></td>
  </tr>
  <% end %>

</table>